name: testing_env36
channels:
  - CIMCB
  - defaults
dependencies:
  - certifi=2019.11.28=py36_1
  - pip=20.0.2=py36_1
  - python=3.6.5
  - setuptools=46.1.1=py36_0
  - wheel=0.34.2=py36_0
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.3
    - chardet==3.0.4
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dicom==0.9.9.post1
    - entrypoints==0.3
    - idna==2.9
    - importlib-metadata==1.5.0
    - ipydatawidgets==4.0.1
    - ipykernel==5.2.0
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipyvolume==0.5.2
    - ipywebrtc==0.5.0
    - ipywidgets==7.5.1
    - jedi==0.16.0
    - jinja2==2.11.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.0
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - nibabel==2.5.1
    - nilearn==0.5.2
    - notebook==6.0.3
    - numpy==1.18.2
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pickleshare==0.7.5
    - pillow==7.0.0
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.4
    - pydicom==1.4.1
    - pygments==2.6.1
    - pyparsing==2.4.6
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pythreejs==2.2.0
    - pyzmq==19.0.0
    - qtconsole==4.7.1
    - qtpy==1.9.0
    - requests==2.23.0
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.14.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.4
    - traitlets==4.3.3
    - traittypes==0.2.1
    - urllib3==1.25.8
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0

